proyecto/decharla/urls.py
from django.urls import path

from . import views

urlpatterns=[
	path('',views.index,name='index'),
	path('login/', views.loggedIn),
	path('favicon.ico', views.get_favicon, name='favicon'),
	path('logout/', views.logout_vista),
	path('sala/<str:sala_id>',views.sala,name="sala"),
	path('sala/<str:sala_id>/json',views.sala_json),
	path('sala/<str:sala_id>/din',views.sala_din),
	path('sala/<str:sala_id>/xml',views.sala_xml),
	path('configuracion/',views.configuracion),
	path('ayuda/',views.ayuda),


]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView as login
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('decharla.urls')),
    path('acceso_admin/',login.as_view())
]

proyecto/decharla/models.py
from django.db import models
from django.utils import timezone

class Sala(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return "El nombre de la sala es: " + str(self.nombre)


class Clave(models.Model):
    clave=models.TextField()
    def __str__(self):
        return "La clave es :"
class Usuario(models.Model):
    escalas=[
        ('pequeño','small'),
        ('mediano','medium',),
        ('grande','large')
    ]
    fuente_letra=[
        ('Arial','Arial'),
        ('Times New Roman','Times New Roman'),
        ('Calibri','Calibri'),
        ('Impact','Impact')
    ]
    nombre=models.CharField(max_length=30,default="Anonimo")
    cookie_id=models.TextField()
    ultima_conexion=models.DateTimeField()
    escala_letra=models.CharField(max_length=30,choices=escalas,default='small')
    tipo_letra=models.CharField(max_length=30,choices=fuente_letra,default='Arial')

    def __str__(self):
        return "El usuario es: " + str(self.nombre) + " con Cookie_Id: " + str(self.cookie_id) + \
               " y conectado por última vez: " + str(self.ultima_conexion)


class Mensaje(models.Model):
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    texto = models.TextField()
    imagen = models.BooleanField(default=False)
    fecha = models.DateTimeField()

    def __str__(self):
        return "Autor: " + self.autor.nombre + ", en sala " + self.sala.nombre


class Visita(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    sala= models.ForeignKey(Sala, on_delete=models.CASCADE)
    ultima_conexion = models.DateTimeField(default=timezone.now)

    def __str__(self):
       return "La visita es del usuario"+self.usuario.nombre + "en la sala" +self.sala.nombre

proyecto/decharla/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404 ,HttpResponseNotAllowed, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Sala,Mensaje,Usuario,Clave,Visita
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.db import models
from django.utils import timezone
import uuid
from xml.dom.minidom import parse
import xml.etree.ElementTree as ET
# Create your views here.

def contador_pie_pagina():
    salas_totales=Sala.objects.all().count()
    fotos_totales=Mensaje.objects.filter(imagen=True).count()
    mensajes_totales= Mensaje.objects.filter(imagen=False).count()
    return salas_totales,mensajes_totales,fotos_totales

def actualizar_visita_sala(cookie_id,sala_id):
    usuario = Usuario.objects.get(cookie_id=cookie_id)#No es necesario controlar si existe controlado fuera
    sala=Sala.objects.get(nombre=sala_id)#No es necesario controlar si existe controlado fuera
    try:
        visita=Visita.objects.get(usuario=usuario,sala=sala)
        visita.ultima_conexion=timezone.now()
        visita.save()
    except Visita.DoesNotExist:
        visita=Visita(usuario=usuario,sala=sala,ultima_conexion=timezone.now())
        visita.save()

@csrf_exempt
def index(request):
    if "cookie_id" in request.COOKIES:
        cookie_id=request.COOKIES.get("cookie_id")
    else:
        return redirect("/login/")
    usuario=Usuario.objects.get(cookie_id=cookie_id)
    usuario.ultima_conexion=timezone.now()
    usuario.save()
    if request.method in ["GET", "POST"]:
        if request.method=="POST":
            try:
                nombre_sala=request.POST["sala"]
                Sala.objects.get(nombre=nombre_sala)
                redireccion = "sala/" + nombre_sala
                return redirect(redireccion)
            except Sala.DoesNotExist:
                sala = Sala(nombre=nombre_sala)
                sala.save()
                redireccion = "sala/" + nombre_sala
                return redirect(redireccion)
        if request.method == "GET":
            salas = Sala.objects.all()
            usuario = Usuario.objects.get(cookie_id=cookie_id)
            salas_totales, mensajes_totales, fotos_totales=contador_pie_pagina()
            contexto = {
                'usuario': usuario,
                'salas': salas,
                'salas_totales':salas_totales,
                'mensajes_totales':mensajes_totales,
                'fotos_totales':fotos_totales,
            }
            return render(request, 'decharla/index.html', contexto)
    else:
        return HttpResponseNotAllowed(['POST','GET'])
@csrf_exempt
def sala(request, sala_id):
    if "cookie_id" in request.COOKIES:
        cookie_id = request.COOKIES.get("cookie_id")
    else:
        return redirect("/login/")
    usuario = Usuario.objects.get(cookie_id=cookie_id)
    usuario.ultima_conexion = timezone.now()
    usuario.save()
    try:#Comprobar si la sala existe
        sala=Sala.objects.get(nombre=sala_id)#haces una busqueda,necesitas el tipo sala para buscar en la foreign key
    except Sala.DoesNotExist:
        return Http404("La sala no existe")
    actualizar_visita_sala(cookie_id,sala_id)
    if request.method in ["PUT","POST"]:#procesar solicitudes put y post
       if request.method=="POST":
           action=request.POST["action"]
           if action=="enviar mensaje":
               texto=request.POST["texto"]
               if 'es_imagen' in request.POST:
                   # La casilla de verificación está seleccionada
                   imagen = True
               else:
                   # La casilla de verificación no está seleccionada
                   imagen = False
               fecha = timezone.now()
               autor=Usuario.objects.get(cookie_id=cookie_id)
               mensaje=Mensaje(sala=sala,autor=autor,texto=texto,imagen=imagen,fecha=fecha)
               mensaje.save()
           elif action=="enviar sala":
               try:
                   nombre_sala = request.POST["sala"]
                   Sala.objects.get(nombre=nombre_sala)
                   redireccion = '/sala/'+nombre_sala
                   return redirect(redireccion)
               except Sala.DoesNotExist:
                   sala = Sala(nombre=nombre_sala)
                   sala.save()
                   redireccion = '/sala/'+nombre_sala
                   return redirect(redireccion)
           elif action=="online":
               redireccion = '/sala/'+sala_id+"/din"
               return redirect(redireccion)
           elif action=="json":
               redireccion = '/sala/' + sala_id + "/json"
               return redirect(redireccion)
    salas_totales, mensajes_totales, fotos_totales = contador_pie_pagina()
    try:#procesar GET
        mensajes = Mensaje.objects.filter(sala=sala)
    except Mensaje.DoesNotExist:
        usuario = Usuario.objects.get(cookie_id=cookie_id)
        contexto = {
            'sala': sala,
            'usuario': usuario,
            'salas_totales': salas_totales,
            'mensajes_totales': mensajes_totales,
            'fotos_totales': fotos_totales
        }
        return render(request, 'decharla/sala.html', contexto)
    usuario = Usuario.objects.get(cookie_id=cookie_id)
    contexto = {
        'mensajes': mensajes,
        'sala':sala,
        'usuario': usuario,
        'salas_totales': salas_totales,
        'mensajes_totales': mensajes_totales,
        'fotos_totales': fotos_totales
    }
    return render(request, 'decharla/sala.html', contexto)


def loggedIn(request):
    if request.method in ["GET","POST"]:
        if request.method=="POST":
            # Obtener la contraseña ingresada en el formulario
            clave = request.POST['clave']
            try:
                Clave.objects.get(clave=clave)
                cookie_id = str(uuid.uuid4())# Generar un UUID único
                ultima_conexion=timezone.now()
                usuario=Usuario(cookie_id=cookie_id,ultima_conexion=ultima_conexion)
                usuario.save()
                response =redirect('/')
                response.set_cookie('cookie_id', cookie_id)
                return response
            except Clave.DoesNotExist:
                contexto={
                    'error':'contraseña incorrecta',
                }
                return render(request, 'decharla/login.html',contexto,status=401)

        else:#GET
            if "cookie_id" in request.COOKIES:
                cookie_id = request.COOKIES.get("cookie_id")
                return redirect('/')
            else:
                return render(request, 'decharla/login.html')
    else:
        return HttpResponseNotAllowed(['POST','GET'])

def logout_vista(request):
    if request.method=="GET":
        if "cookie_id" in request.COOKIES:
            cookie_id = request.COOKIES.get("cookie_id")
            response = redirect('/login')
            response.delete_cookie("cookie_id")
            usuario = Usuario.objects.get(cookie_id=cookie_id)
            usuario.delete()
            return response
        else:#No deberia pasar pero si borra la cookie mientras esta en la pagina
            return redirect("/login/")
    else:
        return HttpResponseNotAllowed('GET')

def configuracion(request):
    if "cookie_id" in request.COOKIES:
        cookie_id = request.COOKIES.get("cookie_id")
    else:
        return redirect("/login/")
    usuario = Usuario.objects.get(cookie_id=cookie_id)
    usuario.ultima_conexion = timezone.now()
    usuario.save()
    if request.method in ["GET", "POST"]:
        if request.method=="POST":
            action = request.POST["action"]
            if action=="enviar nombre":
                nombre=request.POST["nombre"]
                usuario.nombre=nombre
                usuario.save()
            elif action=="enviar tipografia":
                tipo_letra = request.POST["tipo letra"]
                escala_letra = request.POST["escala letra"]
                usuario.tipo_letra = tipo_letra
                usuario.escala_letra = escala_letra
                usuario.save()
            elif action == "enviar sala":
                try:
                    nombre_sala = request.POST["sala"]
                    Sala.objects.get(nombre=nombre_sala)
                    redireccion = '/sala/' + nombre_sala
                    return redirect(redireccion)
                except Sala.DoesNotExist:
                    sala = Sala(nombre=nombre_sala)
                    sala.save()
                    redireccion = '/sala/' + nombre_sala
                    return redirect(redireccion)
    salas_totales, mensajes_totales, fotos_totales = contador_pie_pagina()
    contexto={
        'usuario':usuario,
        'salas_totales': salas_totales,
        'mensajes_totales': mensajes_totales,
        'fotos_totales': fotos_totales
    }
    return render(request, 'decharla/configuracion.html', contexto)
@csrf_exempt
def sala_json(request,sala_id):
    if "cookie_id" in request.COOKIES:
        cookie_id = request.COOKIES.get("cookie_id")
    else:
        return redirect("/login/")
    usuario = Usuario.objects.get(cookie_id=cookie_id)
    usuario.ultima_conexion = timezone.now()
    usuario.save()
    try:#Comprobar si la sala existe
        sala=Sala.objects.get(nombre=sala_id)#haces una busqueda,necesitas el tipo sala para buscar en la foreign key
    except Sala.DoesNotExist:
        return Http404("La sala no existe")
    actualizar_visita_sala(cookie_id,sala_id)
    if request.method=="GET":
        try:
            sala=Sala.objects.get(nombre=sala_id)
        except Sala.DoesNotExist:
            sala = Sala(nombre=sala_id)
            sala.save()
        mensaje_lista=Mensaje.objects.filter(sala=sala)
        mensajes_data=[]
        for mensaje in mensaje_lista:
            mensaje_json= {
                "author": mensaje.autor.nombre,
                "text": mensaje.texto,

proyecto/templates/decharla/ayuda.html
{% extends "decharla/esquema.html" %}
{% block content %}
    <h4>
      En esta sección, encontrarás toda la información y asistencia necesaria para sacar el máximo provecho de
      nuestra plataforma de chat en línea.
        <br><br>
        Nuestro objetivo es brindarte el apoyo necesario para resolver
        cualquier duda o dificultad que puedas encontrar durante tu experiencia en nuestro sitio.
        <br><br>
        ¡Disfruta de tus conversaciones y explora todo lo que DeCharla tiene para ofrecerte!
        <br><br>
      1-Registrate para tener acceso a la pagina y personaliza tu experiencia en ella configurando tu nombre
      y el tipo de tamaño y letra disponible que deseas utilizar clickando en el icono de configuracion.
        <br><br>
      2-Para comunicarte puedes crear una nueva sala o acceder a las disponibles
        <br><br>
      3-Dentro de estas podras enviar mensajes y votar los que mas te gusten.
    </h4>
{% endblock %}

proyecto/templates/decharla/configuracion.html
{% extends "decharla/esquema.html" %}
{% block content %}
    <h1>Configuracion</h1>
    <div class="col">
    <!-- Formulario para escribir el nombre -->
        <form action="" method="POST">
            {% csrf_token %}
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required value={{usuario.nombre}}>
            <br><br>
            <input type="submit" name="action" value="enviar nombre">
        </form>
    <hr>
    </div>
    <div class="col">
        <form action="" method="POST">
            {% csrf_token %}
        <!-- Primer formulario con pestaña desplegable -->

            <label for="opcion1">Tipo de letra:</label>
            <select id="opcion1" name="tipo letra" required>
                #<option value="{{usuario.tipo_letra}}" selected>Actual: {{usuario.tipo_letra}}</option>
                <option value="Arial">Arial</option>
                <option value="Times New Roman">Times New Roman</option>
                <option value="Calibri">Calibri</option>
                <option value="Impact">Impact</option>
            </select>
            <br><br>

    <!-- Segundo formulario con pestaña desplegable -->

            <label for="opcion2">Tamaño de letra:</label>
            <select id="opcion2" name="escala letra" required>
                <option value="{{usuario.escala_letra}}"  selected>Actual: {{usuario.escala_letra}}</option>
                <option value="small">Pequeño</option>
                <option value="medium">Mediano</option>
                <option value="large">Grande</option>
            </select>
            <br><br>
            <input type="submit" name="action" value="enviar tipografia">
        </form>
    </div>
{% endblock %}

proyecto/templates/decharla/esquema.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<style>
    .principal {
        font-family: {{usuario.tipo_letra}};
        font-size: {{usuario.escala_letra}};
    }
</style>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'decharla/css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header class="cabecera">
        <div class="row">
            <h1 class="title"><a href="/" style="text-decoration:none; color: #FF00FF">DeCharla</a></h1>
        </div>
    </header>
    <div class="menu">
        <div class="row border">
                <div class="col-3 border">
                     {% if request.path == '/' %}
                        <h2>Principal</h2>
                    {%else%}
                        <h2><a href="/" style="text-decoration:none; color:#f9f9f9">Principal</a></h2>
                    {% endif %}
                </div>
                <div class="col-3 border">
                    {% if request.path == '/configuracion' %}
                        <h2>Configuracion</h2>
                    {%else%}
                        <h2><a href="/configuracion" style="text-decoration:none; color:#f9f9f9">Configuracion</a></h2>
                    {% endif %}
                </div>
                <div class="col-3 border">
                    {% if request.path == '/ayuda' %}
                        <h2>Ayuda</h2>
                    {%else%}
                        <h2><a href="/ayuda" style="text-decoration:none; color:#f9f9f9">Ayuda</a></h2>
                    {% endif %}
                </div>
                <div class="col-3 border">
                    {% if request.path == '/admin' %}
                        <h2>Admin</h2>
                    {%else%}
                        <h2><a href="/admin" style="text-decoration:none; color:#f9f9f9">Admin</a></h2>
                    {% endif %}
                </div>

            </div>
    </div>
    <div class="principal">
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
        <div class="usuario">
            Tu nombre de charlador es: {{usuario.nombre}}
            <form action="" method="POST">
                {% csrf_token %}
                Nombre de la sala: <input type="text" name="sala">
                <input type="submit" name="action" value="enviar sala">
            </form>
            <button class="btn btn-secondary mt-3" onclick="window.location.href = '/logout';">Logout</button>
        </div>
        </div>
    </div>
    <div class="wrapper border col order-md-3 order-lg-3">
            <footer class="footer">
                <p style="padding-left: 50px;">Salas totales: {{ salas_totales }} |
                    Total mensajes: {{ mensajes_totales }} |
                    Total de fotos: {{ fotos_totales }}
                </p>
                </div>
                <p>&copy; 2023</p>
            </footer>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

proyecto/templates/decharla/index.html
{% extends "decharla/esquema.html" %}
{% block content %}
    <div class="salas_lista">
        <h3>Lista de salas</h3>
        {%if salas %}
            <ul>
                {% for sala in salas %}
                    <li><a href="/sala/{{sala.nombre}}" style="text-decoration:none; font-weight: bold; color:saddlebrown">{{sala.nombre}}</a>
                        Total mensajes: {{ sala.mensaje_set.count }}
                        
                        </li>
                {% endfor %}
            </ul>
        {%else%}
            <p>No tienes salas</p>
        {%endif%}
    </div>
{% endblock %}

proyecto/templates/decharla/login.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/css/bootstrap.min.css">
</head>
<body>
    <div class="inicio container">
        <h1>Iniciar sesión</h1>
        <form method="POST" action="/login/">
            {% csrf_token %}
            <div class="mb-3">
                <label for="clave" class="form-label">Contraseña:</label>
                <input type="password" id="clave" name="clave" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Iniciar sesión</button>
        </form>
        {% if error %}
            <div class="alert alert-danger mt-3">Contraseña incorrecta</div>
        {% endif %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

proyecto/templates/decharla/sala.html
{% extends "decharla/esquema.html" %}
{% block content %}
    <div style=display-flex  class="formulario_sala">
        <div class="left">
            El nombre de la sala es: {{sala.nombre}}
            <form action="" method="POST">
                {% csrf_token %}
                Introduce tu mensaje: <input type="text" name="texto"/>
                <input type="checkbox" name="es_imagen" value="1"/>¿Es una imagen?
                <input type="submit" name="action" value="enviar mensaje"/>
            </form>
        </div>
        <br><br>

        <div style="width: 30%;margin-left: auto; margin-right: auto;" class="right">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" name="action" value="online">
            </form>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" name="action" value="json">
            </form>
        </div>
    </div>

    <div class="lista-mensajes">
        {%if mensajes %}
            <ul>{% for mensaje in mensajes reversed %}
                <ul>
                    <br>
                        Autor:{{mensaje.autor.nombre}}
                    </br>
                    <br>
                        {% if mensaje.imagen %}
                            <img src="{{mensaje.texto}}" alt="Imagen no disponible" class="imagen">
                        {%else%}
                            {{mensaje.texto}}
                        {%endif%}
                    </br>
                        <br>
                        {{mensaje.fecha}}
                        <br>
                    </ul>
                {% endfor %}
            </ul>
        {%else%}
            <p>No tiene mensajes aun esta sala </p>
            <p style="font-size:100px">&#128531</p>
        {%endif%}
    </div>
{% endblock %}

proyecto/templates/decharla/sala_dinamica.html
{% extends "decharla/esquema.html" %}
{% load static %}
{% block content %}
    <div style=display-flex  class="formulario_sala">
        <div class="left">
            El nombre de la sala es: {{sala.nombre}}
            <form action="" method="POST">
                {% csrf_token %}
                Introduce tu mensaje: <input type="text" name="texto"/>
                <input type="checkbox" name="es_imagen" value="1"/>¿Es una imagen?
                <input type="submit" name="action" value="enviar mensaje"/>
            </form>
        </div>
        <br><br>

        <div style="width: 30%;margin-left: auto; margin-right: auto;" class="right">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" name="action" value="normal">
            </form>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="submit" name="action" value="json">
            </form>
        </div>
    </div>
    <div class="lista_mensajes">
        {%if mensajes %}
            <ul>
                <div id="messages"></div>
            </ul>
        {%else%}
            <p>No tiene mensajes aun esta sala </p>
            <p style="font-size:100px">&#128531</p>
        {%endif%}
    </div>
    <script>
        const url_messages = '/sala/{{ sala.nombre }}/json';
    </script>
    <script src="{% static 'decharla/js/script.js' %}"></script>

{% endblock %}